name: ncscolor
description: A comprehensive Dart package for converting NCS (Natural Color System) colors to RGB, HSL, and HEX formats, with additional RGB conversion utilities.
version: 1.0.0
repository: https://github.com/MohamedAbd0/ncscolor
homepage: https://github.com/MohamedAbd0/ncscolor
documentation: https://github.com/MohamedAbd0/ncscolor/blob/main/README.md

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
